### ISSUE TITLE
LLVM 10 is not available in Homebrew

### ISSUE THREAD

**Issue by miraliahmadli** [prosyslab-classroom/llvm-primer#2]
I was trying to test my code and tried to run the commands mentioned in Installation page.

LLVM 10 is not available in Homebrew : https://formulae.brew.sh/formula/

Opam also supports up to LLVM 11.

So it would be good if you changed that part in Installation page to available version (e.g llvm@11).

```
brew install llvm@11  
opam install llvm.11.0.0
```

**Comment by KihongHeo** [comment]
Thanks for your suggestion.
